### ISSUE TITLE
Cache and Promse.all

### ISSUE THREAD

**Issue by bartoszgolebiowski** [ava/use-http#211]
Cache does not work properly, Promise.all() results are undefined and only last one from Promise.all is actually a correct value.
![image](https://user-images.githubusercontent.com/39523638/77111798-3c3ba780-6a28-11ea-9168-0baeaa90cb19.png)

Time to time it works well, sometime You will revived 3 times undefined.

https://codesandbox.io/s/charming-feynman-hxxws

Just change routing, and checked consol logs

All values should be an cached objects, without any undefined.

**Comment by alex-cory** [comment]
Interesting. Okay, I will have a look as soon as possible.

**Comment by alex-cory** [comment]
Found a fix. Stay tuned

**Comment by alex-cory** [comment]
should work in `v1.0`
