### ISSUE TITLE
[Feature Request] Post non JSON request

### ISSUE THREAD

**Issue by seno5979** [ava/use-http#232]
How to post a non JSON request using use-http ?

I'm unable to post a text/plain request using useFetch.

**Comment by alex-cory** [comment]
I'm trying to understand how `axios` does this because here's the problem.

```js
const { post } = useFetch()
// how do we distinguish between
post('/my-route')
// and
post('some data')
```

**Comment by alex-cory** [comment]
Looks like axios requires a relative route.
```js
axios.post('/route', 'whatever')
```
so, we could do it that way
```js
post('/', 'whatever')
```
thoughts?

**Comment by alex-cory** [comment]
Also, going off what axios is doing, I will might eventually do something like
```js
const config = {
  // as a last attempt if needed to overwrite anything in the config
}
post('/route', 'data', config)
```
Not sure how I feel about this though...

**Comment by alex-cory** [comment]
should be available in `v1.0`

**Comment by seno5979** [comment]
Hi,
There still issue when posting a raw text using this library.

When posting "some-data"
By using use-http:
it will send ""some-data"" (receiving unexpected double quote on request body)
This is not happening when using useAxious

**Comment by alex-cory** [comment]
Fixing!
