### ISSUE TITLE
response interceptor doesn't fire when results are loaded from cache

### ISSUE THREAD

**Issue by pwelter34** [ava/use-http#235]
**Describe the bug**
When `cachePolicy: CachePolicies.CACHE_FIRST`, the response interceptor doesn't get called when the results are read from cache, ie the second time its called. 

**⚠️ Make a Codesandbox ⚠️**
I've tweaked the useFetch + <Provider /> + Request/Response Interceptors demo to reproduce.  

https://codesandbox.io/s/usefetch-provider-requestresponse-interceptors-6zwmw

**To Reproduce**

1. let page run first time
2. after loaded, click re-fetch button
3. data read from cache
4.  the data is not transformed using the response interceptor

**Expected behavior**

the response interceptor should be called even if the data is read from cache.

**Comment by alex-cory** [comment]
Great catch, I will take a look at this asap

**Comment by alex-cory** [comment]
I just need to write tests, and then I'll merge this bugfix.

**Comment by alex-cory** [comment]
this is available in `v1.0.1`
