### ISSUE TITLE
loading bug with cache?

### ISSUE THREAD

**Issue by alex-cory** [ava/use-http#237]
https://codesandbox.io/s/usefetch-provider-pagination-exttg?file=/src/index.js

**Comment by alex-cory** [comment]
Just edit the codesandbox, and you'll see `loading` stuck.
Also, I think [this line](https://github.com/ava/use-http/blob/master/src/useFetch.ts#L110) might cause a bug for pagination when we run out of things to fetch because if we set `loading` to true, and we don't set `loading` to false after that, `loading` will get stuck in a true state.

**Comment by alex-cory** [comment]
1. I'm unable to reproduce the bug in that codesandbox locally. Must be a codesandbox issue.
2. Still need to take a look at the `hasMore` pagination potential bug.

**Comment by jnterry** [comment]
I think I have recreated this (or at least a very similar) issue without using codesandbox through using react-router. 

The issue occurs when switching pages. If the user user returns to a page with a previously executed useFetch the `loading` state is stuck true.

Here is a demo with minimal changes from a create-react-app application: https://github.com/jnterry/use-http-bug-demo/blob/master/src/App.js

Steps to recreate:
1. Clone the repo linked above and `npm install`
2. Run `npm run start`
3. In browser, click "Go to B" - this will trigger the fetch and display the JSON content
4. Click "Go To A" to simulate a user navigating to a different page
5. Click "Go To B" - > "Loading..." will be perpetually shown as `fetch.loading` is stuck true, even though `fetch.data` has content. I would expect `fetch.loading` to be false, and the content to be displayed
6. F5 to reload the page - the fetch will be re-triggered

This was tested with node v12.13.0 on a Debian 10 machine.

**Comment by alex-cory** [comment]
I think this issue has the potential to be fixed in #251 . I changed the way caching was being handled and I'm pretty sure it was being caused by the `forceUpdate`. I will get to this as soon as possible.

**Comment by alex-cory** [comment]
This seems to be fixed as of `v1.0.8`. Let me know if the issue persists and I'll reopen the issue.
