### ISSUE TITLE
Handle Refresh token

### ISSUE THREAD

**Issue by dmkav** [ava/use-http#238]
Hi, I like your lib and base my app on it. However, I met some problems trying to implement refresh token logic.
First of all I hold useHttp options in store, where I can easily handle errors/notifications etc. Among options I have retries set to 1 and retryOn set to function that checks 401 status in response.
So, in case of error I get a response with status 401. Right at the response interceptor I check it and make token refresh. Then retry function fires and new token works in successful path. However in bad case, when refresh token fails I can't make influence on retry function and return false. It sends request still.
The point is to get rid of this useless requests. Do you know how I can do it? or perhaps, make retryOn func async?

Thanks in  advance

**Comment by alex-cory** [comment]
Hm... I can make `retryOn` async. It would be nice to have a code example so I can see what you are looking for.

**Comment by alex-cory** [comment]
I'm gonna take a stab at this even though it's a little unclear.
```js
const FetchProvider = ({ children }) => {
  const [token, setToken] = useLocalStorage('api-token')
  const [request, response] = useFetch('https://your-token-api-endpoint.com/token', {
    retryOn: [401],
    retries: 1
  })
  const globalOptions = {
    interceptors: {
      async request(options) {
        if (isExpired(token)) {
          const newToken = await request.get()
          if (response.ok) {
            setToken(newToken)
          } else {
            console.error('there was a problem authenticating the user')
          }
        }
        options.headers.Authorization = `Bearer ${token}`
        return options
      }
    }
  }
}

const App = () => {
  return (
    <FetchProvider>
      <RestOfYourApp />
    </FetchProvider>
  )
}
```

**Comment by dmkav** [comment]
@alex-cory, thank you for response. yeah, right your example is good and it solves one problem - I can get access to abort request. However, there are some more. Let me explain what I have on current stage.
Our app does not have expiration time, so I have to wait until 401 error comes. I don't want to bombing the server with requests, I was trying to stop requests that were sent during token refreshing (I can't stop request that was launched). My code below does it. However I could not abort request or skip them in retryOn func in case of failed token refresh.
That's why i'm thinking about possibility to have access to AbortController instance in request interceptor and to add additional options in response interceptor which will be used in retryOn func. Otherwise handle token refresh in async retryOn function.
```
interceptors: {
    request: async (options) => {
        if (this.isRefreshing) {
            await this.placeIntoWaitingQueue();
            // abort in case of failed token refresh
        }

        const token = this.storage.token;
        if (token) {
            options.headers.Authorization = `Bearer ${token}`;
        }
        return options
    },

    response: async (response: any) => {
        const {ok, data, status} = response;

        if (!ok) {
            if (status === 401) {
                if (!this.isRefreshing) {
                    const result = await this.handleUnauthorizedResponse();
                    if (!result) {
                        this.general.logout();
                        //  Add/pass options to retryOn func
                    }
                    this.processQueue(result);
                } else {
                    return await this.placeIntoWaitingQueue(response);
                }
            } else {
                this.notify.error(data.error);
            }
        }
        return response;
    }
},
retries: 1,
retryOn: [401],
```

Or maybe you could suggest more elegant solution. I would be glad:)

**Comment by alex-cory** [comment]
Does this solve your problem? If so, the `async retryOn` needs to be implemented, but I can do that super fast.
```js
import useFetch, { Provider } from 'use-http'

const FetchProvider = props => {
  const [token, setToken] = useLocalStorage('api-token')
  const [request, tokenResponse] = useFetch('https://your-token-api-endpoint.com/token')

  const globalOptions = {
    retryOn: async ({ response }) => {
      if (response.status === 401) {
         const newToken = await request.get()
          if (tokenResponse.ok) {
            setToken(newToken)
            return true
          } else {
            console.error('there was a problem authenticating the user')
            return false
          }
      }
    },
    retries: 1,
    interceptors: {
      request(options) {
        options.headers.Authorization = `Bearer ${token}`
        return options
      }
    }
  }
  return <Provider {...props} url='https://your-root-url.com' options={globalOptions} />
}

const App = () => {
  return (
    <FetchProvider>
      <RestOfYourApp />
    </FetchProvider>
  )
}
```

**Comment by dmkav** [comment]
yeah, async retryOn would be nice implementation! Thank you.

**Comment by alex-cory** [comment]
I will get that done today

**Comment by alex-cory** [comment]
Once all the checks pass, I'll merge and publish

**Comment by alex-cory** [comment]
This should be available in `v1.0.3`. If you're having any more issues with it, let me know and I'll reopen the issue.

**Comment by SyFlo** [comment]
Hi @alex-cory - first of all, thanks for this awesome lib!

I have the exact same issue and tried to solve it in the same way you described in your answer https://github.com/ava/use-http/issues/238#issuecomment-613712454
my implementation is basically like your example, but when the request is retried, it uses the old token rather than the new one. 
Could it be that the retried request uses the same headers as the original request and doesn't go through the interceptor?

**Comment by veloware** [comment]
Im also getting the same result, setting a token in state is not picked up my the next request interceptor

**Comment by dennib** [comment]
Same here, I've tried something very similar to [#238](https://github.com/ava/use-http/issues/238#issuecomment-613712454) (refreshing tokens once expired inside `retryOn`, sadly the following requests keep on mantaining previous headers.

Any suggestions? Thank you 🙏
