### ISSUE TITLE
Custom error object

### ISSUE THREAD

**Issue by YassienW** [ava/use-http#248]
Right now the error object returns data associated with the status of the failed requested (status code and name). In most of my use cases the server returns an error message that is displayed to the user. The only way i can consume this message now is by adding an extra state hook for the error and setting it manually. 

It would be great if the error object could be leveraged to pass on the error message. Perhaps a function can be passed that provides the response details or body and can be used to either construct a custom error object or add properties to the current error object.

**Comment by alex-cory** [comment]
Hm... what do you mean `the server returns an error message`? Could you provide an example of this `error message`? Are you saying if your backend responds with an error, you get a valid response back say `200` and in that you have some error message? If that is the case you could do something like.

```js
const { error } = useFetch({
  interceptors: {
    response: async ({ response, data }) => { // could add `data` field here
      if (data.message == 'your custom error') throw Error(data.message)
      return response
    }
  }
})
```
That would set the `error` inside `useFetch`

**Comment by YassienW** [comment]
The server returns an error code, but it also returns the specific error message in the response body. The interceptor isn't working because `response.data` is undefined. If there is a way to access the response body on 4xx status then i could make this work.

**Comment by alex-cory** [comment]
Hmmm... Do you wanna try taking a stab at it? [here's how](https://github.com/ava/use-http/blob/master/.github/contributing.md).

**Comment by YassienW** [comment]
I have a problem that only occurs once i add `<Provider/>` component to create-react-app, i get the following error:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

**Comment by alex-cory** [comment]
if worst comes to worst run `rm -rf node_modules` in `use-http-sandbox` then run `yarn` then `cd ../use-http` then
```sh
npm link ../use-http-sandbox/node_modules/react
npm link ../use-http-sandbox/node_modules/react-dom
```
did you run the `npm link` part? You need to follow the [directions](https://github.com/ava/use-http/blob/master/.github/contributing.md#2-environment-setup) in order. 🙂

**Comment by alex-cory** [comment]
@YassienW any luck?

**Comment by YassienW** [comment]
Yes, i have figured out how to add this and now fixing some tests
