### ISSUE TITLE
Request interceptor does not use up-to-date values.

### ISSUE THREAD

**Issue by CaveSeal** [ava/use-http#262]
**Describe the bug**
The request interceptor is stuck using the initial value of a variable in its outer environment.

**⚠️ Make a Codesandbox ⚠️**
https://codesandbox.io/s/pedantic-paper-in770

**To Reproduce**
1. Open the console.
2. Click on increment.
3. The count is not up-to-date in the interceptor.

**Expected behavior**
In my specific use case, a user would configure a value, which should be added to the headers for all requests. When the value changes, I would expect the options to be up-to-date with that change, including the interceptors.

(Sorry if the explanation is lacking)

I think part of the reason may be the inability of JSON.stringify to do function comparison.
https://github.com/ava/use-http/blob/87c0ef1f67905b3ecec1cdbcf0bd98349e4997d6/src/utils.ts#L235

Looks similar to #135

**Comment by alex-cory** [comment]
Will get to this as soon as possible! Bare with me!

**Comment by CaveSeal** [comment]
I discovered that I've been overlooking a much simpler solution to my problem, which is to use globalOptions.headers to add my request header value. Pretty obvious when you think about it.

I'm going to close this issue, since #268 talks about something similar.
