### ISSUE TITLE
Cannot overwrite useFetch urls within a Provider that already has a url set

### ISSUE THREAD

**Issue by altruisticsoftware** [ava/use-http#264]
Heyo!

We have a `<Provider url={OUR_API_URL} />`, which is all fine and dandy, however if I'd like to utilize `useFetch` for a url aside from the one declared in the provider, how would I go about doing that if it's possible? I noticed the `url` option is only available as a prop for the provider, and the idea of overwriting that for one-offs would be great.

_Edit_
I'd like to leverage the additional functionality of the library, which is why using some other http mechanism is not ideal.

**Comment by alex-cory** [comment]
You should be able to just do `useFetch('https://example.com')` is that not working?

**Comment by alex-cory** [comment]
It checks for `://` in the url. If it has that, then it will overwrite the url, otherwise it will add to the url specified in the Provider.

**Comment by altruisticsoftware** [comment]
You sir, are correct. Derp. Thanks!
