### ISSUE TITLE
Can't set cachePolicy due to TypeScript

### ISSUE THREAD

**Issue by Akswii** [ava/use-http#266]
**Describe the bug**
When trying to set cachePolicy to one of the supported variants I get an error from typescript saying the given cachePolicy doesn't match what's defined in cachePolicy. If i import the cachePolicy enum from your project and use the `as CachePolicies` cast then it's ok.

**⚠️ Make a Codesandbox ⚠️**
https://codesandbox.io/s/react-typescript-o1wqx

**To Reproduce**
1. Go to the codesandbox
2. Scroll down to the useFetch call

**Expected behavior**
Being able to set cachePolicy

**Comment by alex-cory** [comment]
```ts
import * as React from "react"
import { render } from "react-dom"
import { useFetch, CachePolicies } from "use-http"

const App = () => {
  const { loading, error, data = [] } = useFetch(
    "https://example.com/todos",
    { cachePolicy: CachePolicies.NO_CACHE },
    []
  )

  return (
    <div>
      <p>Hello world</p>
    </div>
  )
}

render(<App />, document.getElementById("root"))
```

**Comment by alex-cory** [comment]
You expect to be able to set `cachePolicy` as a string of `'no-cache'` instead of using the `CachePolicies.NO_CACHE` enum?

**Comment by Akswii** [comment]
Ah i see. Just me being inexperienced with enums. Tried googling but I guess my search was off. Thanks for a swift answer 😄
