### ISSUE TITLE
Question: testing guidelines

### ISSUE THREAD

**Issue by hiraldesai** [ava/use-http#273]
I wasn't able to find any testing guidelines in the docs. Any reference I can follow? I'm using @testing-library/react + Jest on a create-react-app typescript template.

Is the guideline to do a 1) `jest.mock("use-http", () =>...)` or something along those lines 2) mock fetch on global 3) use a library like `jest-fetch-mock` as mentioned in #261

**Comment by alex-cory** [comment]
That is correct! Eventually I'd like to take a look at some other libraries such as [nock](https://github.com/nock/nock) in the future, but for now you've got it. If you're getting stuck and things don't seem to be working as expected, just set the cache policy to `'no-cach'` or `CachePolicies.NO_CACHE`. `import { CachePolicies } from 'use-http'`
