### ISSUE TITLE
GET requests are cached, regardless of settings

### ISSUE THREAD

**Issue by tobyl** [ava/use-http#281]
**Describe the bug**
This might not be a bug, but following the docs does not appear to resolve this issue. Apologies for no codesandbox - hopefully the issue is clear enough from the example below.

I have a component along the lines of:

```
const FetchContact = () => {

  const request = useFetch('', {
    headers: getHeaders(), // sets csrftoken and 'Content-Type': 'application/json'
    cache: 'no-cache',
  })

  const fetchAccount = useCallback(async () => {
    console.log('triggering new fetch')
    const contact = await request.get(`/api/contacts/`)
  })

  ...
  ...
}
```

The response is different based upon the logged in user - however the call is cached (by the browser I think) even if I set `no-cache`. If I add a timestamp to the URL the call is made and the response is as expected.

**Expected behavior**

Adding `cache: no-cache` should prevent the request/response from being cached. The call is always cached, regardless of the settings applied.

**Comment by StuwiiDev** [comment]
Hey, the correct setting is { cachePolicy: 'no-cache' } . I used this and it works fine. Doc ref is https://use-http.com/#/?id=hooks

**Comment by tobyl** [comment]
@StuwiiDev thank you so much! I'm not sure where I got that original setting from, apologies.
