### ISSUE TITLE
Request.get can i reset the host with and ways

### ISSUE THREAD

**Issue by nick121212** [ava/use-http#288]
Request.get can i reset the host with and ways. ex: request.get("https://github.com")

**Comment by nick121212** [comment]
if then the url is dynamic, sometimes provided by backend. and triggered by the click event

**Comment by alex-cory** [comment]
`useFetch('github.com')` is another way

**Comment by nick121212** [comment]
i have a requirement, when i click the product in the list, send an ajax call with the field which provided by server. so i think i can't use the useFetch hook in the click function. any suggests. @alex-cory
