### ISSUE TITLE
Cache never expires if data is fetched from cache more often than `cacheLife`

### ISSUE THREAD

**Issue by eirikrye** [ava/use-http#294]
**Describe the bug**
Calling get() at a rate higher than `cacheLife` will ensure the data is never considered stale, and will serve the original cached data indefinitely.

**⚠️ Make a Codesandbox ⚠️**

https://codesandbox.io/s/quizzical-albattani-05zfb?file=/src/App.js

**To Reproduce**
1. Open URL above
2. Observe that only a single network request is made over time, despite the setInterval.
3. Click the `get()` button once every couple seconds (faster than `cacheLife`), and  observe that only a single network request is made over time.
4. Change `cachePolicy` to `no-cache` and observe that both the button and timer works properly without cache.

**Expected behavior**
Cache should be considered stale `cacheLife` milliseconds after the original network request was completed, and the data was originally cached.

In the case above, the `setInterval` timer should ensure the data is refreshed on its second tick (after 6000ms). A user clicking the `get()` button quickly should see the data update every `cacheLife` interval.

**Comment by eirikrye** [comment]
The offending code is here:

https://github.com/ava/use-http/blob/c96145651c109e1241343982ae72cd8ad49189d4/src/useFetch.ts#L134

Data is resubmitted to the cache indiscriminately, without checking if the data was already sourced from cache.

**Comment by benarmston** [comment]
I'm experiencing issues with this too.  If I've followed the code through correctly, changing the check to

```
if (!response.isCached && cachePolicy === CACHE_FIRST) {
...
```

Would a PR implementing that change likely be accepted?  I don't want to go to the trouble of setting up TypeScript and creating the PR if it won't be.

**Comment by alex-cory** [comment]
Absolutely
