### ISSUE TITLE
NPM versions missing from GitHub

### ISSUE THREAD

**Issue by philo23** [ava/use-http#295]
**Describe the bug**
While trying to review the latest version of the code available on NPM after seeing an available update, I noticed that the latest version of this package available on NPM is v1.0.15. Here on GitHub however I can only find releases up to v1.0.8, but there also seems to be some tags for v1.1 and v1.2 from last year.

Any idea whats happened and where I can find the source for v1.0.15, which looks like it was published 14 days ago according to NPM?

**⚠️ Make a Codesandbox ⚠️**
N/A

**To Reproduce**
Compare versions available:
https://www.npmjs.com/package/use-http?activeTab=versions
https://github.com/ava/use-http/releases
https://github.com/ava/use-http/tags

**Expected behavior**
The source code should be visible in GitHub, or at least available under releases.

**Comment by alex-cory** [comment]
It's what is currently in the github repo.

**Comment by philo23** [comment]
Fair enough, is there any kind of change log available for the versions on NPM? That's all I was really hoping to find under the releases/tags just to avoid any surprises after updating.

**Comment by alex-cory** [comment]
This was what was changed in the last release https://github.com/ava/use-http/pull/277#issuecomment-700305525
