### ISSUE TITLE
Feature Request: Support React 17.x (and create-react-app 4.x)

### ISSUE THREAD

**Issue by ericlowry** [ava/use-http#299]
Hello!

  I just bootstrapped a new project using `npx create-react-app client` and I tried to `npm install --save use-http` and it blows up with the following:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: client@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from use-http@1.0.15
npm ERR! node_modules/use-http
npm ERR!   use-http@"*" from the root project
npm ERR! 
```

So it looks like use-http has a dependency on React@16...

I would love to be able to use the latest and greatest from React.

Thanks,
Eric

BTW - thanks for making and supporting one of my favorite hooks!

**Comment by ericlowry** [comment]
Ok - a bit of a clarification here.  I don't like using yarn.  I tend to switch to npm... something like this:

```
npx create-react-app client
cd client
rm yarn.lock
rm -rf node_modules
npm install
npm install --save use-http
```

The last step is where it fails... :-(

**Comment by alex-cory** [comment]
Sorry for the delay. Lots of things going on right now. Just tried with yarn and works fine. Can you paste your `package-lock.json`

**Comment by ericlowry** [comment]
Hey Alex,

  Thanks for taking a peek at this - I did mange to get everything working, I just change my Dockerfile to be "yarn aware".

E.
