### ISSUE TITLE
Render occur multiple times

### ISSUE THREAD

**Issue by GomatoX** [ava/use-http#309]
**Describe the bug**
Using use-http single call to endpoint trigers component to rerender three times, instead of two.

**⚠️ Codesandbox ⚠️**
https://codesandbox.io/s/pedantic-frog-sovey?file=/src/App.js

**Expected behavior**
Component should render two times instead of three ( or it's unwritten behaviour ).

(Edited)

**Comment by alex-cory** [comment]
Will review asap

**Comment by luis9laguna** [comment]
Is there a reason why it renders so many times?
