### ISSUE TITLE
Ability to send all possible HTTP request methods

### ISSUE THREAD

**Issue by toburger** [ava/use-http#310]
The following HTTP request methods are defined:
https://developer.mozilla.org/de/docs/Web/HTTP/Methods

I need to send an OPTIONS request to an API, but I'm not able to define an OPTIONS fetch.
Even tough I overwrite the `method` property I am not able to make an OPTIONS request.

#### Currently

```javascript
const { get, ...rest } = useFetch(url, { method: "options" }, [])
...
await get() // always uses `GET`
```

#### Proposal

It would be nice to have a e.g. `req` property that gets returned by `useFetch` that allows me to make a call and it uses the `method` defined in it's options. Basically it has the same functionality as `get` but it respects the `method` setting.

```javascript
const { req, ...rest } = useFetch(url, { method: "options" }, [])
...
await req() // uses the method defined in options
```

#### Alternative proposal

Alternatively add `options`, `head`, ... as properties returned by `useFetch`.

```javascript
const { options, ...rest } = useFetch(url)
...
await options() // uses `options` request method
```

**Comment by alex-cory** [comment]
Should be pretty easy to implement, would definitely accept a PR! Let me know if you need guidance.

**Comment by toburger** [comment]
I've created a PR with my second proposal.
