### ISSUE TITLE
How to use useFetch in getServerSideProps? (Next.js)

### ISSUE THREAD

**Issue by Leonardo-Figueiredo** [ava/use-http#312]
Is there any way to use "useFetch" with getServerSideProps?

![image](https://user-images.githubusercontent.com/32230299/107276335-9921c100-6a31-11eb-88aa-7a087c67bcd2.png)

**Comment by alex-cory** [comment]
Hooks cannot be called from within `getServerSideProps`. Only from inside a react function component. See the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions) part of the react documentation.

**Comment by khusamov** [comment]
How to perform rendering on the server? The use Fetch function only works on the server. As a result, the promised does not work: **SSR (server side rendering) support**
