### ISSUE TITLE
interceptors.response there is not option how toget original request

### ISSUE THREAD

**Issue by herisn23** [ava/use-http#319]
When im using interceptor for response i need to acces to original request, bc i need log request/response to external library. but i do not know how to get RequestInit from response interceptor.

Pls add something like this.

`
interceptors: {
        response:  async({response, request}) => response
      }
`

**Comment by alex-cory** [comment]
Feel free to submit a PR. That doesn't sound too difficult to implement.

**Comment by nebarf** [comment]
@alex-cory 
What's the **request shape** do you suggest to use in **response interceptor**? Do you think an object that matches  standard fetch options is enough (i.e. https://github.com/ava/use-http/blob/master/src/utils.ts#L97)?

**Comment by alex-cory** [comment]
This should be available in `v1.0.22`
