### ISSUE TITLE
Getting this error when sending api request: TypeError: res.current is not an Object. (evaluating ''data' in res.current')

### ISSUE THREAD

**Issue by manidlou** [ava/use-http#326]
Thank you for this library! I just cannot use `use-http` in my react native app! I am just trying to send a simple api request but I keep getting this error!

I am sending the request like this:
```
const { loading, error, data } = useFetch('/some/api/url/', {}, [])
```
and this is the error that I get:
```
TypeError: res.current is not an Object. (evaluating ''data' in res.current')
``` 
Do I have to send data from my server in a certain format to work with `use-http`? I appreciate if anyone would help me with this! Thank you!

**Comment by alex-cory** [comment]
Were you able to figure out the problem @manidlou?
