### ISSUE TITLE
Questions about the future of this package

### ISSUE THREAD

**Issue by JasonMan34** [ava/use-http#338]
I've been using this package for a project of mine for the past 2 months and I am very satisfied with it, but it's missing some key features for me

I'd love to contribute to this package if it's being maintained and supported, but is it?  
I want to add some tests but the current tests fail for me locally, and `npm run lint` returns 53 problems.  
If I made PRs fixing those issues would they be addressed?

**Comment by alex-cory** [comment]
absolutely
