### ISSUE TITLE
no-cors mode?

### ISSUE THREAD

**Issue by t3db0t** [ava/use-http#343]
Does/can useFetch expose the fetch `no-cors` mode? Or is there a better way to deal with cors issues (i.e. making api calls from localhost) in development?

**Comment by alex-cory** [comment]
Did you not try adding that in the options?

**Comment by t3db0t** [comment]
I actually did, and it may have worked, but I realized my problem was serverside. Nonetheless, it wouldn't hurt to put `no-cors` mode in the docs :)
